kind: ConfigMap
apiVersion: v1
metadata:
  name: nginxconf
data:
  authInfo.yaml: |
    {{ range .Values.authInfo }}
    realm: {{ .realm }}
    client: {{ .client }}
    clientSecret: {{ .clientSecret }}
    {{ end }}
