apiVersion: v1
kind: Service
metadata:
  name: demix-pg
  labels: { { - include "dd-keycloak.labels" . | nindent 4 } }
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "dd-keycloak.selectorLabels" . | nindent 4 } }
