apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "dd-keycloak.fullname" . }}-nginx-rp
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "dd-keycloak.fullname" . }}-nginx-rp
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ include "dd-keycloak.fullname" . }}-nginx-rp
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginxRP.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        volumeMounts:
          - name: nginxconf
            mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginxconf
        configMap:
          name: nginxconf