apiVersion: v1
kind: Service
metadata:
  name: {{ include "dd-keycloak.authApp.service.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: {{ include "dd-keycloak.authApp.service.port" . }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ include "dd-keycloak.fullname" . }}-auth-app