apiVersion: v1
kind: Service
metadata:
  name: {{ include "dd-keycloak.nginx-rp.service.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ include "dd-keycloak.fullname" . }}-nginx-rp